USE clinica_medica_node;

ALTER TABLE consultas
ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'agendada' AFTER descricao;

ALTER TABLE consultas
ADD COLUMN observacao_status VARCHAR(255) NULL AFTER status;

ALTER TABLE consultas
ADD COLUMN data_criacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER observacao_status;

ALTER TABLE consultas
ADD COLUMN data_atualizacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER data_criacao;

ALTER TABLE pacientes
ADD COLUMN cpf VARCHAR(20) NULL AFTER telefone,
ADD COLUMN email VARCHAR(100) NULL AFTER cpf;

ALTER TABLE medicos
ADD COLUMN crm VARCHAR(20) NULL AFTER especialidade,
ADD COLUMN email VARCHAR(100) NULL AFTER crm;

DESCRIBE consultas;